# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Need to use Node to build the angular things
    - name: Use Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: AWS cli install action
      uses: chrislennon/action-aws-cli@1.1

    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-southeast-2

    - name: Install Dependencies
      run: npm ci

    # Runs a single command using the runners shell
    - name: Angular Build
      run: npm run build:prod

    # Runs a set of commands using the runners shell
    - name: S3 Copy
      run: aws s3 cp dist/untitled s3://${{ secrets.AWS_BUCKET_NAME }}/ --recursive

    # Runs a set of commands using the runners shell
    - name: Cloudfront Invalidate
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DIST_ID }} --paths "/*"
